name: Test comtypes with latest CPython
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Clone CPython repository
        run: git clone --depth 1 https://github.com/python/cpython.git
      - name: Build CPython
        working-directory: ./cpython
        run: PCbuild\build.bat -p x64 -c Release
      - name: Clone comtypes from GH upstream repo
        run: git clone https://github.com/enthought/comtypes.git
      - name: Unittest
        run: |
          cd comtypes/
          ..\cpython\PCbuild\amd64\python.exe -m unittest discover -v -s ./comtypes/test -t comtypes\test
