name: Test comtypes with latest CPython
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download and Extract CPython Zip
        run: |
          $url = "https://github.com/sergey-miryanov/cpython/archive/refs/heads/gh-100926-ctypes-pointers-cache.zip"
          $output = "cpython.zip"
          Invoke-WebRequest -Uri $url -OutFile $output
          Expand-Archive -Path $output -DestinationPath .
          Rename-Item -Path "cpython-gh-100926-ctypes-pointers-cache" -NewName "cpython"
      - name: Build CPython
        working-directory: ./cpython
        run: PCbuild\build.bat -p x64 -c Release
      - name: Clone comtypes from GH upstream repo
        run: git clone https://github.com/enthought/comtypes.git
      - name: Unittest
        run: |
          cd comtypes/
          ..\cpython\PCbuild\amd64\python.exe -m unittest discover -v -s ./comtypes/test -t comtypes\test
